---
webserver:
  addr: "0.0.0.0"
  port: "8080"
postgres:
  host: "urlshtn-go_postgres_db_1"
  port: "5432"
  database: "url_shortener"
  username: "local-user"
  password: "123Change"
  sslmode: "disable"